-- Test tenant data for company search functionality

INSERT INTO tenants (
  id,
  name,
  slug,
  theme_color,
  subscription_status,
  subscription_plan,
  feature_flags,
  trial_start,
  trial_ends,
  industry,
  size,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'Acme Corporation',
  'acme-corporation',
  '#6C2EBE',
  'active',
  'professional',
  '{"cold_calls": true, "chat": true, "documents": true}',
  NOW() - INTERVAL '5 days',
  NOW() + INTERVAL '9 days',
  'Technology',
  'Medium',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Global Real Estate Inc',
  'global-real-estate-inc',
  '#2563EB',
  'active',
  'starter',
  '{"cold_calls": true, "chat": false, "documents": false}',
  NOW() - INTERVAL '3 days',
  NOW() + INTERVAL '11 days',
  'Real Estate',
  'Small',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'TechFlow Solutions',
  'techflow-solutions',
  '#059669',
  'trialing',
  'enterprise',
  '{"cold_calls": true, "chat": true, "documents": true}',
  NOW() - INTERVAL '1 day',
  NOW() + INTERVAL '13 days',
  'Technology',
  'Large',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Dubai Properties Group',
  'dubai-properties-group',
  '#DC2626',
  'active',
  'professional',
  '{"cold_calls": true, "chat": true, "documents": true}',
  NOW() - INTERVAL '7 days',
  NOW() + INTERVAL '7 days',
  'Real Estate',
  'Large',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Innovation Labs',
  'innovation-labs',
  '#7C3AED',
  'trialing',
  'starter',
  '{"cold_calls": true, "chat": false, "documents": false}',
  NOW() - INTERVAL '2 days',
  NOW() + INTERVAL '12 days',
  'Technology',
  'Medium',
  NOW(),
  NOW()
);
