import theme from '../../../design-system/modulyn-theme.json'

export const DESIGN = {
  sidebarWidth: 260,
  headerHeight: 64,
  borderRadius: '12px',
  fontSize: {
    base: '14px',
    title: '18px',
  },
  colors: {
    primary: theme.functional.primary.default,
    accent: theme.functional.highlight.default,
    background: theme.functional.surface.primary,
    backgroundDark: theme.personalized.obsidianVeil,
    surface: theme.functional.surface.secondary,
    surfaceDark: theme.personalized.charcoalTint,
    card: theme.functional.surface.primary,
    cardDark: theme.personalized.charcoalTint,
    text: theme.functional.onSurface.strong,
    textDark: theme.semantic.text.onDark,
    textSecondary: theme.functional.onSurface.soft,
    textSecondaryDark: theme.semantic.text.onDark,
    textDisabled: theme.semantic.text.disabled,
    textDisabledDark: theme.semantic.text.disabled,
    divider: theme.semantic.fields.border,
    dividerDark: theme.semantic.fields.border,
  },
  logo: {
    height: 32,
    width: 120,
  },
  signupPage: {
    background: theme.functional.surface.primary,
    leftCol: {
      background: theme.functional.surface.secondary,
      logoHeight: 'auto',
      logoWidth: 200,
      brandColor: theme.functional.primary.default,
      brandFontSize: '22px',
      textColor: theme.functional.onSurface.strong,
      contactBlock: {
        labelColor: theme.functional.primary.default,
        valueColor: theme.functional.onSurface.strong,
        fontSize: '14px',
        spacing: '1.5rem',
      },
      socialIcon: {
        size: 24,
        bg: theme.functional.surface.primary,
        border: `1px solid ${theme.functional.primary.default}`,
        color: theme.functional.primary.default,
        radius: '50%',
        margin: '0 0.5rem',
      },
    },
    rightCol: {
      background: theme.functional.primary.default,
      maxWidth: 520,
      padding: '2rem',
      borderRadius: '16px',
      boxShadow: '0 4px 32px 0 rgba(0, 0, 0, 0.08)',
    },
    header: {
      color: theme.functional.primary.onPrimary,
      fontSize: '1.5rem',
      fontWeight: 700,
      marginBottom: '2rem',
      textAlign: 'center',
    },
    input: {
      fontSize: '16px',
      color: theme.functional.primary.onPrimary,
      border: 'none',
      borderBottom: `2px solid ${theme.semantic.fields.border}`,
      borderRadius: 0,
      background: 'transparent',
      padding: '0.75rem 0',
      marginBottom: '2rem',
      focusBorder: theme.semantic.fields.focusBorder,
      placeholderColor: theme.semantic.fields.placeholder,
    },
    label: {
      fontSize: '16px',
      color: theme.functional.primary.onPrimary,
      fontWeight: 600,
      marginBottom: '0.5rem',
    },
    button: {
      background: theme.functional.surface.primary,
      color: theme.functional.primary.default,
      borderRadius: '8px',
      fontSize: '18px',
      fontWeight: 700,
      padding: '0.75rem',
      marginTop: '1.5rem',
      boxShadow: '0 2px 8px 0 rgba(108,46,190,0.10)',
    },
    progress: {
      dotActive: theme.functional.onSurface.strong,
      dotInactive: theme.functional.surface.primary,
      size: 12,
      spacing: '0.75rem',
      marginTop: '2.5rem',
    },
    error: {
      color: '#E53E3E',
      fontSize: '13px',
      marginTop: '0.25rem',
    },
  },
  loginPage: {
    background: '#EDEADE',
    leftCol: {
      background: '#090004', // Form area (bold)
      logoHeight: 'auto',
      logoWidth: 200,
      brandColor: '#EDEADE',
      brandFontSize: '22px',
      textColor: '#EDEADE',
      contactBlock: {
        labelColor: '#EDEADE',
        valueColor: '#FFFFFF',
        fontSize: '14px',
        spacing: '1.5rem',
      },
      socialIcon: {
        size: 24,
        bg: '#090004',
        border: '1px solid #EDEADE',
        color: '#EDEADE',
        radius: '50%',
        margin: '0 0.5rem',
      },
    },
    rightCol: {
      background: '#EDEADE', // Branding area (light)
      boxBg: '#090004',
      maxWidth: 520,
      padding: '2rem',
      borderRadius: '16px',
      boxShadow: '0 4px 32px 0 rgba(0, 0, 0, 0.08)',
    },
    header: {
      color: '#090004', // Form header text color (bold)
      fontSize: '1.5rem',
      fontWeight: 700,
      marginBottom: '2rem',
      textAlign: 'center',
    },
    input: {
      fontSize: '16px',
      color: '#090004',
      border: 'none',
      borderBottom: '2px solid #E5E7EB',
      borderRadius: 0,
      background: 'transparent',
      padding: '0.75rem 0',
      marginBottom: '2rem',
      focusBorder: '#6C2EBE',
      placeholderColor: '#A0AEC0',
    },
    label: {
      fontSize: '16px',
      color: '#090004',
      fontWeight: 600,
      marginBottom: '0.5rem',
    },
    button: {
      background: '#090004',
      color: '#EDEADE',
      borderRadius: '8px',
      fontSize: '18px',
      fontWeight: 700,
      padding: '0.75rem',
      marginTop: '1.5rem',
      boxShadow: '0 2px 8px 0 rgba(108,46,190,0.10)',
    },
    error: {
      color: '#E53E3E',
      fontSize: '13px',
      marginTop: '0.25rem',
    },
  },
}; 